spring:
  application:
    name: oauth2
  datasource:
    url: jdbc:mysql://oauth-db:3306/test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vadli
    password: vadli
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8085
